# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160520_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Our_event',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Our_work',
            new_name='Work',
        ),
    ]
